# Generated by Django 4.2.3 on 2023-07-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('ageGroup', models.CharField(max_length=500)),
                ('startDate', models.DateField(max_length=200)),
                ('endDate', models.DateField(max_length=200)),
                ('time', models.TimeField(max_length=200)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
